### ISSUE TITLE
Envoi d'une image

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#11]
Pour le moment l'ajout d'incrust ne gère que l'ajout d'une url pour télécharger l'image.
L'envoi d'une image (par exemple capture faite en locale sur la machine) serait utile

voir express-fileupload : https://github.com/richardgirges/express-fileupload

**Comment by NicolasBrondin** [comment]
Et les images seraient enregistrées sur le serveur node ou dans un Bucket S3 ?

**Comment by chriscamicas** [comment]
Les images sont actuellement stockées en local dans MongoDB.
Ce choix est important pour ne pas avoir une latence à l'affichage lors de l'enregistrement (et l'affichage de l'incrust) mais aussi si on a besoin d'enregistrer en offline. 
Et en plus c'est gratuit, on a pas forcément envie de se rajouter des frais d'hébergement pour ce service. Sauf s'il y a un valeur ajoutée à héberger ça

**Comment by mtthp** [comment]
réalisé dans https://github.com/chriscamicas/girr/pull/39
par contre, l'upload d'une image assez lourde (10MB) ralentit l'interface (sur la page d'un Episode). J'espère que ce ne sera pas souvent le cas, sinon il faudra compresser dynamiquement les images coté serveur pour les servir de manière optimale au client.
