### ISSUE TITLE
Sécurisation de l'accès

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#12]
Pouvoir sécuriser l'accès au serveur web qu'aux membres de GeekInc
Page de login ?
OAuth via Google ?

le login via Google serait pratique notamment pour pouvoir le lier avec des GoogleDocs

**Comment by NicolasBrondin** [comment]
Avec PassportJS par exemple?

https://scotch.io/tutorials/easy-node-authentication-google

:)

**Comment by chriscamicas** [comment]
Merci et c'est absolument ce à quoi je pensais.
Pas envie de gérer les users en local, et l'auth Google me va bien.

**Comment by NicolasPopy** [comment]
Pourquoi une sécurisation ? Je pensais que c'était censé fonctionner qu'en local entre une tablette posée sur la table et un RPI au studio.

**Comment by chriscamicas** [comment]
Afin de pouvoir préparer les émissions à distance (créer la liste des news, les titres, saisir les notes, et envoyer les incrusts)

**Comment by NicolasPopy** [comment]
ah ok, j'avais pas "remarqué" cette feature.

**Comment by chriscamicas** [comment]
la doc est en cours
mais sinon c'est indiqué brièvement dans le README :
> Pour le moment, il permet :
> de préparer les sujets et incrusts pour une émission via une page de préparation

**Comment by chriscamicas** [comment]
un simple basic auth, avec un login+mdp en dur général suffirait pour une première version

**Comment by chriscamicas** [comment]
done with 2978318
