### ISSUE TITLE
problèmes de chargements des incrustes

### ISSUE THREAD

**Issue by NicolasPopy** [chriscamicas/girr#20]
Erreur lors du chargement de la page admin.html.
Ne trouve pas le répertoire api/emissions/bits/59/incrusts/ qui n'existe pas dans le projet.

admin.html:100 GET http://localhost:8080/api/emissions/bits/59/incrusts/ 404 (Not Found)
loadIncrust @ admin.html:100
document.addEventListener.event @ admin.html:104

**Comment by chriscamicas** [comment]
la page admin.html est obsolète, il faut utiliser la page emissions.html pour créer/préparer les émissions

**Comment by NicolasPopy** [comment]
La page Emission est vide chez moi.
J'ai juste un bouton Accueil vert.

**Comment by chriscamicas** [comment]
effectivement il faut créer en bdd, manuellement pour le moment les émissions et épisodes
A minima, l'émission bits et l'épisode 59

**Comment by NicolasPopy** [comment]
db.emissions.insertOne({ nom: "bits"})
et
db.episodes.insertOne({numero: 59, emission: ObjectId("5995b16c02ea80762e7b852e")})
avec l'object id correspondant à celui de ton émission que tu as créé précédemment

**Comment by chriscamicas** [comment]
doublon #21
