### ISSUE TITLE
Migration Vue+Webpack

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#25]
Initialement le projet a été fait le plus simple possible.
Cependant, dans le but de faire une vraie webapp, et pouvoir notamment inclure des components tiers, il serait souhaitable de migrer le front vers un 'vrai' projet vue/webpack.
voir https://github.com/vuejs/vue-cli et https://github.com/vuejs-templates/webpack

attention à intégrer ça dans le projet actuel qui contient front+back

**Comment by chriscamicas** [comment]
quelle est la meilleure proposition pour intégrer front (vue/webpack) + back (node/express) dans un seul projet ?
notamment l'architecture des dossiers ?

**Comment by AdrienRedon** [comment]
Un mini projet vue.js + express que j'ai fait : [https://github.com/AdrienRedon/vue-marvel](https://github.com/AdrienRedon/vue-marvel)

Là, le back c'est juste le fichier app.js parce qu'il y a quasi rien mais sinon, faire un dossier app avec le back dedans (mes projets plus conséquents en vue sont comme ça).

Qu'est-ce que t'en penses ?

**Comment by chriscamicas** [comment]
C'est parfait ça !
