### ISSUE TITLE
changement de caméra

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#26]
Depuis la page 'presentateur', un animateur peut changer de caméra 
cf http://xjsframework.github.io/quickstart.html

**Comment by mtthp** [comment]
D'après ce que j'ai compris, il faut créer une extension à importer dans XSplit. Cette extension devra se connecter au serveur GIRR puis envoyer des informations à propos des scènes et recevoir des commandes pour contrôler l'affichage. Du coup, créer un autre projet 'GIRR XSplit extension' ou l'intégrer dans celui-ci ?

**Comment by chriscamicas** [comment]
En effet, j'en comprends la même chose que toi : XSplit importe un page HTML (ou juste du JS) et s'en sert comme extension.
On n'a pas nécessairement besoin de rendre l'extensibilité générique, le changement de caméra et le lancement de générique via XSplit est suffisant pour le moment.
De plus, l'extension doit être servie par un serveur Web (si je comprends bien l'exemple ici  : https://github.com/xjsframework/scene-rotator)
Donc, je propose de l'intégrer dans le même projet (ce sera plus simple à gérer), et de gérer au mieux la séparation du code.

**Comment by chriscamicas** [comment]
Dans l'idée, il faudrait 
- récupérer la liste des scènes de XSplit
- les afficher dans la page utilisée pour la présentation de l'émission (sous forme de boutons)
- au clic sur le bouton, envoyer une demande de changement de scène à XSplit
ceci nous permettra de gérer à la fois les lancement de génériques (on utilise des scènes avec autoplay vidéo), et les changements de caméra (scène classique)

**Comment by mtthp** [comment]
Ok ça marche !

**Comment by chriscamicas** [comment]
Alors, je suis désolé de revenir si tard sur ce point, mais depuis le changement vers Studio Renegade, nous avons complètement revu la manière dont nous tournons les émissions.
Plus de XSplit, mais OBS à la place (plus léger pour la machine), et nous avons investi dans un StreamDeck qui permet justement de commander les changements de plans (entre autre).
On peut donc abandonner ce point, désolé pour le temps que tu as pu y passer

**Comment by chriscamicas** [comment]
ça pourrait rester intéressant, mais moins prioritaire par rapport à d'autres demandes
