### ISSUE TITLE
Avoir un retour visuelle du live

### ISSUE THREAD

**Issue by thehawk970** [chriscamicas/girr#37]
Il serait peut être interessant au moyen d'accessoire connecté (Hue ?) d'avoir un retour visuel: 

Exemple : Si on est dans la scène "classique", que le live twitch est on line et que le micro est activé , alors la lumière est verte,

Green: Scene principale, twitch on, micro on
Yellow: Scene de transition, twitch on, micro on
Orange: Micro off,
Red: Twitch off

**Comment by chriscamicas** [comment]
C'est désormais traité grace au StreamDeck
