### ISSUE TITLE
Titre global

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#4]
Avoir un titre global en plus des titres des news, qui serait le titre de l'émission.
Il sera affiché au démarrage.

**Comment by chriscamicas** [comment]
Depuis l'interface de préparation (page emissions.html pour le moment), créer une page de saisie/modification de l'épisode avec
- numéro
- date de diffusion
- titre global

**Comment by NicolasPopy** [comment]
Il faudrait aussi peut-être prévoir des titres pré-programmés avec le nom des chroniqueurs, leur twitter et pourquoi pas une photo de profil dans un petit rond. Design à voir.

**Comment by chriscamicas** [comment]
bonne idée !
tu peux créer une nouvelle issue pour ça en détaillant le besoin stp ?
merci

**Comment by NicolasPopy** [comment]
Pour la page émission, décider d'un code couleur pour les bandeaux pour chaque émission et le logo en incruste se met à chaque fois.
Du coup, ça demande peut-être dans Xsplit d'avoir 2 pages Html, une toujours présente avec ce logo et une autre pour les titres qui apparaissent/disparaissent.
