### ISSUE TITLE
Positionnement des incrusts à l'affichage

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#41]
A l'affichage (vue XSplit), les incrusts prennent trop de places.
La version précédente disposait de plus de `margin` autour de l'image.
Le rendu visuel était beaucoup mieux

**Comment by mtthp** [comment]
J'ai mis une marge de 1.5em en haut pour avoir le même espace avec le titre qu'avec le bord haut.
J'avais enlevé toute marge de l'image à l'origine car je trouvais dommage de pas avoir les incrustes qui prennent le maximum d'espace, surtout quand on regarde sur un smartphone : je me suis même demandé si il ne serait pas mieux de mettre le titre par dessus. Mais si ça rend plus joli en étant centré, tant mieux :)

**Comment by chriscamicas** [comment]
fixed by #44
