### ISSUE TITLE
Paramétrage des logos des émissions

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#42]
pouvoir modifier le logo de chaque émission
Interface pour envoyer et stocker 2 images par émission
En effet, on a besoin de 2 versions du logo, une en couleur, et une en blanc+transparent pour une intégration dans la vue XSplit

**Comment by mtthp** [comment]
Est-ce qu'une conversion du logo en couleur vers une version blanche serait suffisante ? en utilisant une library telle que avec [jimp](https://github.com/oliver-moran/jimp) or [sharp](https://github.com/lovell/sharp)
ça permettrait aussi de servir les images en plus petites résolutions et alléger l'interface, notamment celle d'un Episode (je pense surtout aux mobiles)

**Comment by chriscamicas** [comment]
C'est une bonne idée ça peut se tester déjà pour voir ce que peut sortir cette lib et comparer aux images que nous avons déjà

**Comment by mtthp** [comment]
J'ai implémenté jimp sur https://github.com/mtthp/girr/tree/topic-43 mais le résultat escompté n'est pas forcément le bon. Voici 2 versions en noir et blanc : 
![logo-2b8920be-8e03-4e6a-ad4e-88a040806e66](https://user-images.githubusercontent.com/3807788/32692894-c0667fe2-c720-11e7-8650-c8bf41094336.png)
![logo-2b8920be-8e03-4e6a-ad4e-88a040806e66-invert](https://user-images.githubusercontent.com/3807788/32692896-c36572ca-c720-11e7-9a9f-fb12cfcdd87f.png)
Je ne sais pas si ça peut convenir, sinon j'ajouterai la possibilité d'uploader un second logo.

**Comment by chriscamicas** [comment]
ah oui effectivement ça ne correspond pas à ce qu'on attend du logo.
Merci pour cet essai, mais je pense que le stockage d'un second logo nous laissera plus de libertés
