### ISSUE TITLE
Changements d'alignement dans les titrages

### ISSUE THREAD

**Issue by Ylesia** [chriscamicas/girr#46]
Mettre le padding du titrage à 10px

**Comment by mtthp** [comment]
Bien sûr, il suffit de changer cette ligne : 
https://github.com/chriscamicas/girr/blob/ea53b125437c3aadc016b6bffd12c59eb4abd934/client/src/components/Xsplit.vue#L122
Il est même possible d'[éditer directement le fichier depuis Github](https://github.com/chriscamicas/girr/edit/master/client/src/components/Xsplit.vue#L122), pas besoin de fork le projet et de faire une pull request :)
Ne pas oublier de build le client une fois les changements effectués pour les répercuter sur la production ;)
