### ISSUE TITLE
Ajouter un bouton pause dans la barre haute

### ISSUE THREAD

**Issue by Ylesia** [chriscamicas/girr#48]
Quand l'émission fait une pause le compteur continue de s'incrémenter pouvons-nous avoir un bouton pour arrêter temporairement le compteur puis le reprendre par la suite.

**Comment by chriscamicas** [comment]
L'intérêt pour nous c'est de garder le temps du live pour générer le timecode des vidéos sur youtube

**Comment by mtthp** [comment]
est-ce que ça vous va si le compteur d'un Episode n'est que la somme des compteurs des Topic ? et du coup, lorsqu'aucun Topic n'est en cours, l'Episode est en pause ?

**Comment by chriscamicas** [comment]
C'est plus compliqué que ça, puisqu'on a souvent un lancement de l'épisode, où on dit bonjour, on raconte des conneries avant de lancer les news
Le besoin est encore à mûrir dans le détail un peu je pense, mais l'idée est de bien de récupérer un simili-timecode des news pour la description youtube par ex

**Comment by mtthp** [comment]
ah d'accord, c'est pour insérer un sommaire dans la description YouTube, je comprends mieux. Le plus simple actuellement, ce serait de mettre un titre "anonyme" via les réglages sans lancer l'Episode et de ne démarrer l'Episode que lorsque le premier générique est lancé, mais ça ne résout pas le problème de pause éventuelle.
