### ISSUE TITLE
Ordre des incrusts

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#49]
L'ordre des incrusts n'est pas conservé et pas logique
(à détailler)

**Comment by mtthp** [comment]
Je n'ai pas compris, pourrais-tu détailler s'il te plaît avec peut-être un gif ou des screenshots ?

**Comment by chriscamicas** [comment]
Exemple : Hugh rajoute 3 incrusts d'un coup pour la météo du matin
il valide, ça les sauve bien, et quand il revient plus tard sur la page de l'emission elles ne sont pas dans l'ordre dans lequel il les a ajouté
Il a même essayé en nommant les fichiers A1, A2, A3 pour voir si le nommage influait
Je n'ai pas pu vérifier/analyser plus que ça

**Comment by mtthp** [comment]
Oui c'est fort possible. Je m'explique : 
- lorsque l'utilisateur ajoute de nouveaux Medias, chaque fichier est envoyé de manière asynchrone
- ils restent néanmoins dans le même ordre car ils sont déjà dans la mémoire du navigateur (donc pas besoin de les recharger)
- mais lorsque l'utilisateur redemande à voir les Medias (recharge la page), ceux-ci sont retournés dans l'ordre de leur position, soit l'**ordre dans lequel ils ont été reçus par le serveur**, qui donc dépend de la taille des fichiers
Je règle ça prochainement. Je reverrai peut-être aussi l'UI en ce qui concerne le changement de l'ordre des Medias, mais j'aimerai avoir plus de retours utilisateur là-dessus.

**Comment by mtthp** [comment]
C'est désormais corrigé en envoyant la position lors de l'ajout d'un nouveau Media https://github.com/chriscamicas/girr/pull/55/commits/c6841ec78c1910dd6e01eda75dfba2c13e75d8dd
