### ISSUE TITLE
Perte du descriptif lors du premier ajout texte + image

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#51]
Si on crée une nouvelle news, et qu'on y met simultanément un descriptif et une ou plusieurs image(s), alors on perd le texte qu'on a saisi

**Comment by mtthp** [comment]
Je n'arrive pas reproduire ce bug, je suis désolé. Est-ce que c'est possible d'avoir les logs du serveur ?

**Comment by chriscamicas** [comment]
je pense que c'est lié au fait qu'on l'utilise à distance, possiblement sur un raspberry pi
donc je pense au fait que la latence pourrait jouer un rôle la dedans
de quel log tu as besoin précisément ? les logs node ?

**Comment by mtthp** [comment]
Oui, les logs NodeJS. Ils sont normalement situés à `server/logs/*.log` sauf si spécifier autrement en variable d'environnement (ou dans `server/config/.env`)

**Comment by mtthp** [comment]
Merci pour les logs. Je ne pense pas avoir mis suffisamment de données pour retracer le comportement provoquant ce bug, mais c'est fortement possible que ce soit lié à la capacité du Raspberry à traiter rapidement les images.
C'est peut-être en lien avec https://github.com/chriscamicas/girr/issues/49, donc je vais regarder ça de plus près.

**Comment by mtthp** [comment]
J'ai trouvé d'où venait le bug et corrigé dans https://github.com/chriscamicas/girr/pull/55/commits/0d3234c28490c010bb801d0f34355da62c1b8c48#diff-76ac1bca0c1db2680b7d6be67ff1ce29L170 : une mauvaise implémentation de ma part de sauvegarder la liste des ids des Medias au sein du Topic dans la DB alors que je ne m'en servais pas.

**Comment by mtthp** [comment]
Résolu, à moins que quelqu'un veuille apporter plus d'informations.

**Comment by chriscamicas** [comment]
fixed
