### ISSUE TITLE
Incrust vidéo

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#53]
Au même titre que les incrusts, on souhaiterait pouvoir afficher des vidéos youtube en incrust
Besoin : 
> - pouvoir rajouter un lien youtube
> - pouvoir inclure le timing du démarrage, ex: https://www.youtube.com/watch?v=GU8svXhlYxA&t=2123s
> - Démarrer la vidéo en automatique quand le player s'affiche en incrust
> - Arrêter la vidéo quand on enlève l'incrust

**Comment by mtthp** [comment]
C'est fait. Pour tout ce qui est des paramètres, c'est à mettre à travers l'URL. Il y a une liste ici : https://developers.google.com/youtube/player_parameters
Par contre, il n'y a pas de contrôle pour la vidéo : pas de play/pause, réglage du volume et autres… Je ne sais pas ce que ça va donner lors des séances de stream.

**Comment by chriscamicas** [comment]
suite à #54 l'incrust youtube a été mise à en place, mais je constate des erreurs de cross-origin sous Chrome :
`Refused to display 'https://www.youtube.com/watch?v=n0o4vMP-o28' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by mtthp** [comment]
Oui c'est tout à fait normal car le seul moyen d'intégrer une vidéo Youtube est par l'url de la forme `https://www.youtube.com/embed/{videoId}`
J'ai ajouté une conversion automatique dans https://github.com/chriscamicas/girr/pull/58 pour pouvoir envoyer des urls standards (comme `https://www.youtube.com/watch?v={videoId}`) et y appliquer des paramètres par défaut comme la lecture automatique.
