### ISSUE TITLE
Refresh après ajout d'une image

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#59]
si on ajoute une image à une news existante, la page de l'épisode ne se met pas à jour et n'affiche pas l'image récemment ajoutée. Si on force le refresh (via F5), l'image devient visible.

**Comment by mtthp** [comment]
Je n'arrive malheureusement pas à reproduire ce bug, et je n'ai pas d'hypothèse sur pourquoi il apparaît 😞

**Comment by mtthp** [comment]
Je soupçonne très fortement que ce soit lié à https://github.com/chriscamicas/girr/pull/62, ce serait bien de retester avec les correctifs.

**Comment by chriscamicas** [comment]
fixed
probablement avec la PR #62
