### ISSUE TITLE
Multiple image et topic en même temps

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/girr#61]
Quand on change de topic ou d'image au sein d'un même topic, le précédent reste actif (allumé/sélectionné).

**Comment by mtthp** [comment]
Je ne suis pas sûr d'avoir tout compris, est-ce que ce serait possible d'avoir un screenshot ?

**Comment by mtthp** [comment]
Problème résolu dans https://github.com/chriscamicas/girr/pull/62.
J'ajouterai prochainement plus de tests unitaires pour aller dans la bonne voie 👍
