### ISSUE TITLE
Pouvoir réordonner les médias d'un sujet

### ISSUE THREAD

**Issue by psegalen** [chriscamicas/girr#68]
Titre explicite ! :D
Bonus : pouvoir choisir le média qui illustre le sujet "collapsed" ! ;)

**Comment by mtthp** [comment]
Ça fonctionne lors de la visualisation d'un sujet, par drag&drop, de la même manière que réordonner les sujets d'un épisode. Par contre ça ne fonctionne pas dans la dialog d'un sujet.

Pour le moment le premier média illustre toujours le sujet.

**Comment by psegalen** [comment]
Ah dis donc ! J'avais pas capté, effectivement c'est un peu sioux mais ça fonctionne !
