### ISSUE TITLE
Chronomètre par sujet mal utilisé

### ISSUE THREAD

**Issue by NicolasPopy** [chriscamicas/girr#70]
Le chronomètre par sujet est actuellement déclenché en cliquant sur Play et Stop pour l'arrêter.
En cliquant sur Play, le titre apparait sur OBS.

En choisissant une image d'illustration, le titre disparait mais en recliquant sur l'image pour l'enlever le titre ne réapparait pas.
Du coup, le streameur clique sur Stop puis Play pour réafficher le titre.
Et alors le chronomètre par sujet repart de zéro. Et du coup, le chronomètre perd de son intérêt.

![regie](https://user-images.githubusercontent.com/4594165/57979895-c17ab800-7a23-11e9-80c2-cafd6e50dcd2.JPG)
Dernier Geek inc avec 2mn par sujet au lieu de 15-20mn.

Idée pour fix ce problème : 
- Faire réapparaitre le titre quand on enlève une image (solution idéale)
- Avoir un bouton afficher le titre à coté de Play et Stop.
- Mettre un bouton "pause" à la place de Stop qui ne remet pas à zéro si on fait play ensuite.

**Comment by mtthp** [comment]
> En choisissant une image d'illustration, le titre disparait mais en recliquant sur l'image pour l'enlever le titre ne réapparait pas.
> Du coup, le streameur clique sur Stop puis Play pour réafficher le titre.

Le titre est toujours affiché sauf dans le cas où le sujet est en mode plein écran, ce qui est le cas dans la plupart des Geek inc pour avoir des images sans marges.

Je suis néanmoins d'accord pour améliorer le compteur, que ce soit sur les épisodes, sujets ou médias. Actuellement, seules une date de début et une date de fin sont stockées : l'idéal serait d'avoir une infinité de couples <début, fin> et d'en faire la somme pour savoir combien de temps un élément a été à l'écran.

**Comment by NicolasPopy** [comment]
L'intérêt premier du compteur pour le streameur, c'est de savoir si un sujet est trop long ou pas.
Et donc il a besoin du temps passé depuis la première ouverture du sujet jusqu'au passage au sujet suivant. 
Sur Geek inc par exemple, théoriquement l'émission est composée de 3-4 sujets de 15-20mn pour faire environ 1H d'émission. Avec le compteur, les intervenants peuvent savoir où ils en sont et conclure au bon moment. 


Quand à l'affichage du titre, devoir appuyer sur Stop puis Play pour le réafficher pour moi, c'est du hack et ce n'est pas une utilisation "normale" de la régie.

**Comment by chriscamicas** [comment]
Je ne comprends pas bien, ça voudrait dire que quand une image est affichée en plein écran et que le titre ne l'est plus, au prochain affichage du titre (sans image), le compteur repart à 0 ?
Si c'est ça, c'est clairement un bug introduit par ma modif sur la gestion du plein écran

**Comment by NicolasPopy** [comment]
Oui et non Christophe.
En fait, pour faire réapparaitre le titre après une image fullscreen (et peut-être pas fullscreen), il faut cliquer sur Stop puis Play. Mais en faisant Play, le compteur repart à 0.

L'utilisation "voulue", c'est que le titre du sujet soit affiché pendant le plan de la caméra et quand il y a une incruste, le titre disparait.
Sauf qu'à la disparition de l'image, le plan avec la caméra est vide, sans titre. Et pour le faire réapparaitre, le streameur est obligé de "reset" le compteur en faisant Stop puis Play.

Pour moi, le bug est que le titre devrait réapparaitre quand on enlève une image et ce n'est pas le cas.

**Comment by chriscamicas** [comment]
AH ! c'est beaucoup plus clair, merci !
ça ressemble à un bug effectivement, mais il me semblait l'avoir fix celui-là

**Comment by NicolasPopy** [comment]
C'est peut-être pas déployé sur le Rpi ?

**Comment by NicolasPopy** [comment]
Bon, j'ai pas envie de batailler avec Git ce soir.
Il faut ajouter cette ligne dans "server/src/routes/media.js" ligne 488

`scene.fullscreen=false`

Testé et ça fonctionne.

**Comment by NicolasPopy** [comment]
#72 corrigé
